#pragma once

#include "wch/hw/def.h"

/******************************************************************************/
/*                     General Alternate Function I/O                         */
/******************************************************************************/

#define AFIO_BASE  APB2PERIPH_BASE

//------------------------------------------------------------------------------

#ifdef __ASSEMBLER__

#define AFIO_PCF1R   4
#define AFIO_EXTICR  8

#else

//------------------------------------------------------------------------------

typedef enum {
  EXTI_PORTA = 0,
  EXTI_PORTC = 2,
  EXTI_PORTD = 3
} exti_port_id_t;

typedef enum {
  AFIO_TIM_RM_NO    = 0x0, /* No remap      (ETR/PC5, CH1/PD2, CH2/PA1, CH3/PC3, CH4/PC4, BKIN/PC2, CH1N/PD0, CH2N/PA2, CH3N/PD1) */
  AFIO_TIM_RM_PART1 = 0x4, /* Partial remap (ETR/PC5, CH1/PC6, CH2/PC7, CH3/PC0, CH4/PD3, BKIN/PC1, CH1N/PC3, CH2N/PC4, CH3N/PD1) */
  AFIO_TIM_RM_PART2 = 0x8, /* Partial remap (ETR/PD4, CH1/PD2, CH2/PA1, CH3/PC3, CH4/PC4, BKIN/PC2, CH1N/PD0, CN2N/PA2, CH3N/PD1) */
  AFIO_TIM_RM_FULL  = 0xC  /* Full remap    (ETR/PC2, CH1/PC4, CH2/PC7, CH3/PC5, CH4/PD4, BKIN/PC1, CH1N/PC3, CH2N/PD2, CH3N/PC6) */
} afio_tim_rm_t;

typedef struct {
       uint32_t RESERVED;
  __IO uint32_t PCFR1;      /* Remap Register 1 */
  __IO uint32_t EXTICR;     /* External Interrupt Configuration Register 1*/
} afio_t;

#define AFIO  ((afio_t *)AFIO_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------

/******************  Bit definition for AFIO_PCFR1 register  *******************/
#define AFIO_SPI1_RM  0x00000001 /* SPI1 remapping */
#define AFIO_I2C1_RM  0x00000002 /* I2C1 remapping */
#define AFIO_UART1_RM 0x00000004 /* UART1 remapping */

/* TIMx remapping */
#define AFIO_TIM1_RM 0x000000C0 /* TIM1_REMAP[7:6] bits */
#define AFIO_TIM2_RM 0x00000300 /* TIM2_REMAP[9:8] bits */
#define AFIO_TIM1_RM_POS 6
#define AFIO_TIM2_RM_POS 8

#define AFIO_PA12_RMP        0x00008000 /* Port D0/Port D1 mapping on OSC_IN/OSC_OUT */
#define AFIO_ADC1_ETRGINJ_RM 0x00020000 /* ADC 1 External Trigger Injected Conversion remapping */
#define AFIO_ADC1_ETRGREG_RM 0x00040000 /* ADC 1 External Trigger Regular Conversion remapping */
#define AFIO_UART1_HIGH_RM   0x00200000 /* UART1 remapping higher bit */
#define AFIO_I2C1_HIGH_RM    0x00400000
#define AFIO_TIM1_IRM        0x00800000

#define AFIO_SWD 0x07000000 /* SWCFG[26:24] bits (Serial Wire IO Debug configuration) */
#define AFIO_SWD_OFF 0x04000000 /* SWD (SDI) disabled */

/*****************  Bit definition for AFIO_EXTICR register  *****************/
#define AFIO_EXTI0 0x00000003 /* [1:0]   EXTI 0 configuration */
#define AFIO_EXTI1 0x0000000C /* [3:2]   EXTI 1 configuration */
#define AFIO_EXTI2 0x00000030 /* [5:4]   EXTI 2 configuration */
#define AFIO_EXTI3 0x000000C0 /* [7:6]   EXTI 3 configuration */
#define AFIO_EXTI4 0x00000300 /* [9:8]   EXTI 4 configuration */
#define AFIO_EXTI5 0x00000C00 /* [11:10] EXTI 5 configuration */
#define AFIO_EXTI6 0x00003000 /* [13:12] EXTI 6 configuration */
#define AFIO_EXTI7 0x0000C000 /* [15:14] EXTI 7 configuration */

#define AFIO_EXTI_POS0 0
#define AFIO_EXTI_POS1 2
#define AFIO_EXTI_POS2 4
#define AFIO_EXTI_POS3 6
#define AFIO_EXTI_POS4 8
#define AFIO_EXTI_POS5 10
#define AFIO_EXTI_POS6 12
#define AFIO_EXTI_POS7 14

//------------------------------------------------------------------------------

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * gadefox, 2026
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
