#pragma once

#include "wch/hw/def.h"

/******************************************************************************/
/*                         MCU Debug Support                                   */
/******************************************************************************/

#define DBG_BASE  (CORE_PERIPH_BASE + 0xD000)

//------------------------------------------------------------------------------

#ifdef __ASSEMBLER__

#define DBG_CFGR0  0
#define DBG_CFGR1  4

#else

//------------------------------------------------------------------------------

typedef struct {
  __IO uint32_t CFGR0;
  __IO uint32_t CFGR1;
} dbg_t;

#define DBG  ((dbg_t *)DBG_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------

/*********************  Bit definition for DBG_CFGR0 register  ******************/

// This register allows the MCU to be configured in the debug state
#define DBG_IWDG_STOP  0x00000001  /* Bit 0 : IWDG stops working when the core enters the debug state */
#define DBG_WWDG_STOP  0x00000002  /* Bit 1 : WWDG stops working when the core enters the debug state */
#define DBG_TIM1_STOP  0x00000010  /* Bit 4 : Timer 1 stops when the core enters the debug state */
#define DBG_TIM2_STOP  0x00000020  /* Bit 5 : Timer 2 stops when the core enters the debug state */

//------------------------------------------------------------------------------

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * gadefox, 2026
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
