#pragma once

#include "wch/hw/base.h"
#include "wch/hw/def.h"

/******************************************************************************/
/*                            ENHANCED FUNCTION                               */
/******************************************************************************/

#define EXTEN_BASE  (AHBPERIPH_BASE + 0x3800)

//------------------------------------------------------------------------------

#ifdef __ASSEMBLER__

#define EXTEN_CTR  0

#else

//------------------------------------------------------------------------------

/* Enhanced Registers */
typedef struct {
  __IO uint32_t CTR;
} exten_t;

#define EXTEN  ((exten_t *)EXTEN_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------

#define EXTEN_LOCKUP_EN   0x00000040 /* Bit 6 */
#define EXTEN_LOCKUP_RSTF 0x00000080 /* Bit 7 */
#define EXTEN_LDO_TRIM    0x00000400 /* Bit 10 */
#define EXTEN_OPA_EN      0x00010000 /* Bit 16 */
#define EXTEN_OPA_NSEL    0x00020000 /* Bit 17 */
#define EXTEN_OPA_PSEL    0x00040000 /* Bit 18 */

//------------------------------------------------------------------------------

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * It was significantly reworked into several files cnlohr, 2025-01-29
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
