#pragma once

#include "wch/hw/def.h"

/******************************************************************************/
/*                    External Interrupt/Event Controller                     */
/******************************************************************************/

#define EXTI_BASE  (APB2PERIPH_BASE + 0x0400)

//------------------------------------------------------------------------------

#ifdef __ASSEMBLER__

#define EXTI_INTENR  0
#define EXTI_EVENR   4
#define EXTI_RTENR   8
#define EXTI_FTENR   12
#define EXTI_SWIEVR  16
#define EXTI_INTFR   20

#else

//------------------------------------------------------------------------------

/* EXTI mode enumeration */
typedef enum {
  EXTI_IRQ   = 0x00,
  EXTI_EVENT = 0x04
} exti_mode_t;

/* EXTI Trigger enumeration */
typedef enum {
  EXTI_TRIG_RISING  = 0x08,
  EXTI_TRIG_FALLING = 0x0C,
  EXTI_TRIG_BOTH    = 0x10
} exti_trigger_t;

typedef struct {
  __IO uint32_t INTENR; /* Interrupt Enable Register            */
  __IO uint32_t EVENR;  /* Event Capture Register               */
  __IO uint32_t RTENR;  /* Rising Edge Trigger Enable Register  */
  __IO uint32_t FTENR;  /* Falling Edge Trigger Enable Register */
  __IO uint32_t SWIEVR; /* Soft Interrupt Event Register        */
  __IO uint32_t INTFR;  /* Interrupt Flag Register              */
} exti_t;

#define EXTI  ((exti_t *)EXTI_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------

#define EXTI_NOPIN 0x0000 /* No interrupt selected */
#define EXTI_PIN0  0x0001 /* External interrupt line 0 */
#define EXTI_PIN1  0x0002 /* External interrupt line 1 */
#define EXTI_PIN2  0x0004 /* External interrupt line 2 */
#define EXTI_PIN3  0x0008 /* External interrupt line 3 */
#define EXTI_PIN4  0x0010 /* External interrupt line 4 */
#define EXTI_PIN5  0x0020 /* External interrupt line 5 */
#define EXTI_PIN6  0x0040 /* External interrupt line 6 */
#define EXTI_PIN7  0x0080 /* External interrupt line 7 */
#define EXTI_PIN8  0x0100 /* External interrupt line 8 connected to the PVD Output */
#define EXTI_PIN9  0x0200 /* External interrupt line 9 connected to the PWR Auto Wake-up event*/

//------------------------------------------------------------------------------

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * gadefox, 2026
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
