#pragma once

#include "wch/hw/def.h"

/******************************************************************************/
/*                           Independent WATCHDOG                             */
/******************************************************************************/

#define IWDG_BASE  (APB1PERIPH_BASE + 0x3000)

//------------------------------------------------------------------------------

#ifdef __ASSEMBLER__

#define IWDG_CTLR   0
#define IWDG_PSCR   4
#define IWDG_RLDR   8
#define IWDG_STATR  12

#else

//------------------------------------------------------------------------------

typedef enum {
  IWDG_KEY_RELOAD = 0xAAAA,  /* Reload counter */
  IWDG_KEY_UNLOCK = 0x5555,  /* Unlock access to PSCR and RLDR registers */
  IWDG_KEY_START  = 0xCCCC   /* Start the watchdog (if HW watchdog not enabled) */
} iwdg_key;

//------------------------------------------------------------------------------

typedef struct {
  __IO uint32_t CTLR;     /* Control Register   */
  __IO uint32_t PSCR;     /* Prescaler Register */
  __IO uint32_t RLDR;     /* Reload Register    */
  __IO uint32_t STATR;    /* Status Register    */
} iwdg_t;

#define IWDG  ((iwdg_t *)IWDG_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------

/*******************  Bit definition for IWDG_PSCR register  ********************/
#define IWDG_DIV    0x0007 /* PR[2:0] (Prescaler divider) */
#define IWDG_DIV4   0x0000
#define IWDG_DIV8   0x0001
#define IWDG_DIV16  0x0002
#define IWDG_DIV32  0x0003
#define IWDG_DIV64  0x0004
#define IWDG_DIV128 0x0005
#define IWDG_DIV256 0x0006

/*******************  Bit definition for IWDG_RLDR register  *******************/
#define IWDG_RL 0x0FFF /* Watchdog counter reload value */

/*******************  Bit definition for IWDG_STATR register  ********************/
#define IWDG_PVU 0x0001 /* Watchdog prescaler value update */
#define IWDG_RVU 0x0002 /* Watchdog counter reload value update */

//------------------------------------------------------------------------------

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * gadefox, 2026
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
