#pragma once

#include "wch/hw/base.h"
#include "wch/hw/def.h"

/******************************************************************************/
/*                           Independent WATCHDOG                             */
/******************************************************************************/

#define IWDG_BASE  (APB1PERIPH_BASE + 0x3000)

//------------------------------------------------------------------------------

#ifdef __ASSEMBLER__

#define IWDG_CTLR   0
#define IWDG_PSCR   4
#define IWDG_RLDR   8
#define IWDG_STATR  12

#else

//------------------------------------------------------------------------------

typedef struct {
  __IO uint32_t CTLR;     /* Control Register   */
  __IO uint32_t PSCR;     /* Prescaler Register */
  __IO uint32_t RLDR;     /* Reload Register    */
  __IO uint32_t STATR;    /* Status Register    */
} iwdg_tf;

#define IWDG  ((iwdg_t *)IWDG_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------

/* CTLR register bit mask */
#define CTLR_KEY_RELOAD 0xAAAA
#define CTLR_KEY_EN     0xCCCC

/*******************  Bit definition for IWDG_CTLR register  ********************/
#define IWDG_KEY 0xFFFF /* Key value (write only, read 0000h) */

/*******************  Bit definition for IWDG_PSCR register  ********************/
#define IWDG_PR  0x07 /* PR[2:0] (Prescaler divider) */
#define IWDG_PR0 0x01 /* Bit 0 */
#define IWDG_PR1 0x02 /* Bit 1 */
#define IWDG_PR2 0x04 /* Bit 2 */

/*******************  Bit definition for IWDG_RLDR register  *******************/
#define IWDG_RL 0x0FFF /* Watchdog counter reload value */

/*******************  Bit definition for IWDG_STATR register  ********************/
#define IWDG_PVU 0x01 /* Watchdog prescaler value update */
#define IWDG_RVU 0x02 /* Watchdog counter reload value update */

/* IWDG_WriteAccess */
#define IWDG_WRITEACCESS_EN  0x5555

/* IWDG_prescaler */
#define IWDG_PRESCALER4   0x00
#define IWDG_PRESCALER8   0x01
#define IWDG_PRESCALER16  0x02
#define IWDG_PRESCALER32  0x03
#define IWDG_PRESCALER64  0x04
#define IWDG_PRESCALER128 0x05
#define IWDG_PRESCALER256 0x06

/* IWDG_Flag */
#define IWDG_FLAG_PVU 0x0001
#define IWDG_FLAG_RVU 0x0002

//------------------------------------------------------------------------------

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * It was significantly reworked into several files cnlohr, 2025-01-29
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
