#pragma once

#include "wch/hw/def.h"

/******************************************************************************/
/*                          Option Bytes Registers                            */
/******************************************************************************/

#define OB_BASE  0x1FFFF800  /* Flash Option Bytes base address */

#ifdef __ASSEMBLER__

#define OB_RDPR   0
#define OB_USER   2
#define OB_DATA0  4
#define OB_DATA1  6
#define OB_WRPR0  8
#define OB_WRPR1  10
#define OB_DATA   12
#define OB_SIZE   64    /* sizoof (User option bytes) = 64 bytes */

#else

//------------------------------------------------------------------------------

typedef struct {
  __IO uint16_t RDPR;
  __IO uint16_t USER;
  __IO uint16_t DATA0;
  __IO uint16_t DATA1;
  __IO uint16_t WRPR0;
  __IO uint16_t WRPR1;
  __IO uint32_t DATA[13];
} ob_t;

#define OB  ((ob_t *)OB_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------

/******************  Bit definition for OB_RDPR register  *******************/
#define OB_RDPR  0x00FF /* Read protection option byte */
#define OB_nRDPR 0xFF00 /* Read protection complemented option byte */

#define OB_RDPR_KEY  0xA5
#define OB_RDPR_nKEY 0x5A

/******************  Bit definition for OB_USER register  ******************/
#define OB_USER  0x00FF /* User option byte */
#define OB_nUSER 0xFF00 /* User complemented option byte */

#define OB_IWDG_SW     0x01 /* Software IWDG selected */
#define OB_STOP_NORST  0x02 /* No reset generated when entering in STOP */
#define OB_STDBY_NORST 0x04 /* No reset generated when entering in STANDBY */

/* Reset IO (PD7) */
#define OB_RST         0x18 /* [4:3] */
#define OB_RST_DT128US 0x00 /* Reset IO enable (PD7) and ignore delay time 128us */
#define OB_RST_DT1MS   0x08 /* Reset IO enable (PD7) and ignore delay time 1ms */
#define OB_RST_DT12MS  0x10 /* Reset IO enable (PD7) and ignore delay time 12ms */

#define OB_START_BOOT 0x20 /* Start in BOOT area */

/******************  Bit definition for OB_DATA Register  *****************/
#define OB_DATA  0x00FF /* User data storage option byte */
#define OB_nDATA 0xFF00 /* User data storage complemented option byte */

/******************  Bit definition for OB_WRPR register  ******************/
#define OB_WRPR  0x00FF /* Flash memory write protection option bytes */
#define OB_nWRPR 0xFF00 /* Flash memory write protection complemented option bytes */

//------------------------------------------------------------------------------

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * gadefox, 2026
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
