#pragma once

#include "wch/hw/def.h"

/******************************************************************************/
/*                          Option Bytes Registers                            */
/******************************************************************************/

#ifdef __ASSEMBLER__

#define OB_BASE  0x1FFFF800  /* Flash Option Bytes base address */

#define OB_RDPR   0
#define OB_USER   2
#define OB_Data0  4
#define OB_Data1  6
#define OB_WRPR0  8
#define OB_WRPR1  10

#else

//------------------------------------------------------------------------------

#define OB_BASE  ((uint32_t)0x1FFFF800) /* Flash Option Bytes base address */

typedef struct {
  __IO uint16_t RDPR;
  __IO uint16_t USER;
  __IO uint16_t Data0;
  __IO uint16_t Data1;
  __IO uint16_t WRPR0;
  __IO uint16_t WRPR1;
} ob_t;

#define OB  ((ob_t *)OB_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------

/* Option_Bytes_IWatchdog */
#define OB_IWDG_SW ((uint16_t)0x0001) /* Software IWDG selected */
#define OB_IWDG_HW ((uint16_t)0x0000) /* Hardware IWDG selected */

/* Option_Bytes_nRST_STOP */
#define OB_STOP_NORST ((uint16_t)0x0002) /* No reset generated when entering in STOP */
#define OB_STOP_RST   ((uint16_t)0x0000) /* Reset generated when entering in STOP */

/* Option_Bytes_nRST_STDBY */
#define OB_STDBY_NORST ((uint16_t)0x0004) /* No reset generated when entering in STANDBY */
#define OB_STDBY_RST   ((uint16_t)0x0000) /* Reset generated when entering in STANDBY */

/* Option_Bytes_RST_ENandDT */
#define OB_RST_NOEN       ((uint16_t)0x0018) /* Reset IO disable (PD7)*/
#define OB_RST_EN_DT12MS  ((uint16_t)0x0010) /* Reset IO enable (PD7) and  Ignore delay time 12ms */
#define OB_RST_EN_DT1MS   ((uint16_t)0x0008) /* Reset IO enable (PD7) and  Ignore delay time 1ms */
#define B_RST_EN_DT128US ((uint16_t)0x0000) /* Reset IO enable (PD7) and  Ignore delay time 128us */

/* Option_Bytes_Power_ON_Start_Mode */
#define OB_POWERON_START_MODE_BOOT ((uint16_t)0x0020) /* from Boot after power on */
#define OB_POWERON_START_MODE_USER ((uint16_t)0x0000) /* from User after power on */

#define OB_START_MODE_BOOT ((uint16_t)0x0020) /* Start in BOOT area */
#define OB_START_MODE_USER ((uint16_t)0x0000) /* Start in user area */

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * It was significantly reworked into several files cnlohr, 2025-01-29
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
