#pragma once

#include "wch/hw/base.h"
#include "wch/hw/def.h"

/******************************************************************************/
/*                     Program Fast Interrupt Controller                      */
/******************************************************************************/

#define PFIC_BASE  (CORE_PERIPH_BASE + 0xE000)

//------------------------------------------------------------------------------

#ifdef __ASSEMBLER__

#define PFIC_ISR       0
#define PFIC_IPR       32
#define PFIC_ITHRESDR  64
#define PFIC_CFGR      72
#define PFIC_GISR      76
#define PFIC_VTFIDR    80
#define PFIC_VTFADDR   96
#define PFIC_IENR      256
#define PFIC_IRER      352
#define PFIC_IPSR      448
#define PFIC_IPRR      544
#define PFIC_IACTR     640
#define PFIC_IPRIOR    864
#define PFIC_SCTLR     2932

#else

//------------------------------------------------------------------------------

/* memory mapped structure for Program Fast Interrupt Controller (PFIC) */
typedef struct {
   __I uint32_t ISR[8];             /* Interrupt Enable Status Register x                  */
   __I uint32_t IPR[8];             /* Interrupt Pending Status Register x                 */
  __IO uint32_t ITHRESDR;           /* Interrupt Priority Threshold Configuration Register */
  __IO uint32_t RESERVED;
  __IO uint32_t CFGR;               /* Interrupt Configuration Register                    */
   __I uint32_t GISR;               /* Interrupt Global Status Register                    */
  __IO uint8_t  VTFIDR[4];          /* VTF ID Configuration Regsite                        */
       uint8_t  RESERVED0[12];
  __IO uint32_t VTFADDR[4];         /* VTF x Offset register                               */
       uint8_t  RESERVED1[0x90];
   __O uint32_t IENR[8];            /* Interrupt Enable Setting Register x                 */
       uint8_t  RESERVED2[0x60];
   __O uint32_t IRER[8];            /* Interrupt Enable Clear Register x                   */
       uint8_t  RESERVED3[0x60];
   __O uint32_t IPSR[8];            /* Interrupt Pending Status Register x                 */
       uint8_t  RESERVED4[0x60];
   __O uint32_t IPRR[8];            /* Interrupt Pending Clear Register x                  */
       uint8_t  RESERVED5[0x60];
  __IO uint32_t IACTR[8];           /* Interrupt Activation Status Register x              */
       uint8_t  RESERVED6[0xE0];
  __IO uint8_t  IPRIOR[256];        /* Interrupt Priority Configuration Register           */
       uint8_t  RESERVED7[0x810];
  __IO uint32_t SCTLR;              /* System Control Register                             */
} pfic_t;

#define PFIC  ((pfic_t *)PFIC_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------

#define PFIC_KEY1 ((uint32_t)0xFA050000)
#define PFIC_KEY2 ((uint32_t)0xBCAF0000)
#define PFIC_KEY3 ((uint32_t)0xBEEF0000)

/* Preemption_Priority_Group */
#define PFIC_PRIORITY_GROUP_0 ((uint32_t)0x00)
#define PFIC_PRIORITY_GROUP_1 ((uint32_t)0x01)
#define PFIC_PRIORITY_GROUP_2 ((uint32_t)0x02)
#define PFIC_PRIORITY_GROUP_3 ((uint32_t)0x03)
#define PFIC_PRIORITY_GROUP_4 ((uint32_t)0x04)

//------------------------------------------------------------------------------

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * It was significantly reworked into several files cnlohr, 2025-01-29
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
