#pragma once

#include "wch/hw/def.h"

/******************************************************************************/
/*                               Power Control                                */
/******************************************************************************/

#define PWR_BASE  (APB1PERIPH_BASE + 0x7000)

//------------------------------------------------------------------------------

#ifdef __ASSEMBLER__

#define PWR_CTLR    0
#define PWR_CSR     4
#define PWR_AWUCSR  8
#define PWR_AWUWR   12
#define PWR_AWUPSC  16

#else

//------------------------------------------------------------------------------

typedef struct {
  __IO uint32_t CTLR;   /* Power Control Register                       */
  __IO uint32_t CSR;    /* Power Control/Status Register                */
  __IO uint32_t AWUCSR; /* Auto-wakeup Control/Status Register          */
  __IO uint32_t AWUWR;  /* Auto-wakeup Window Comparison Value Register */
  __IO uint32_t AWUPSC; /* Auto-wakeup Crossover Factor Register        */
} pwr_t;

#define PWR  ((pwr_t *)PWR_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------

/********************  Bit definition for PWR_CTLR register  ********************/
#define PWR_PDDS  0x00000002 /* Power Down Deepsleep */
#define PWR_PVDE  0x00000010 /* Power Voltage Detector Enable */

/* PVD Level Selection */
#define PWR_PLS      0x000000E0  /* PLS[7:5] bits */
#define PWR_PLS_2V85 0x00000000  /* 2.85V rising / 2.7V falling */
#define PWR_PLS_3V05 0x00000020  /* 3.05V rising / 2.9V falling */
#define PWR_PLS_3V3  0x00000040  /* 3.3V rising  / 3.15V falling */
#define PWR_PLS_3V5  0x00000060  /* 3.5V rising  / 3.3V falling */
#define PWR_PLS_3V7  0x00000080  /* 3.7V rising  / 3.5V falling */
#define PWR_PLS_3V9  0x000000A0  /* 3.9V rising  / 3.7V falling */
#define PWR_PLS_4V1  0x000000C0  /* 4.1V rising  / 3.9V falling */
#define PWR_PLS_4V4  0x000000E0  /* 4.4V rising  / 4.2V falling */

/*******************  Bit definition for PWR_CSR register  ********************/
#define PWR_PVDO 0x00000004 /* PVD Output */

/*******************  Bit definition for PWR_AWUCSR register  ********************/
#define PWR_AWUEN 0x00000002  /* Enable Automatic wake-up */

/*******************  Bit definition for PWR_AWUPSC register  ********************/
#define PWR_AWU          0x0000000F
#define PWR_AWU_OFF      0x00000000
#define PWR_AWU_DIV1     0x00000001
#define PWR_AWU_DIV2     0x00000002
#define PWR_AWU_DIV4     0x00000003
#define PWR_AWU_DIV8     0x00000004
#define PWR_AWU_DIV16    0x00000005
#define PWR_AWU_DIV32    0x00000006
#define PWR_AWU_DIV64    0x00000007
#define PWR_AWU_DIV128   0x00000008
#define PWR_AWU_DIV256   0x00000009
#define PWR_AWU_DIV512   0x0000000A
#define PWR_AWU_DIV1024  0x0000000B
#define PWR_AWU_DIV2048  0x0000000C
#define PWR_AWU_DIV4096  0x0000000D
#define PWR_AWU_DIV10240 0x0000000E
#define PWR_AWU_DIV61440 0x0000000F

//------------------------------------------------------------------------------

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * gadefox, 2026
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
