#pragma once

#include "wch/hw/def.h"

/******************************************************************************/
/*                        Serial Peripheral Interface                         */
/******************************************************************************/

#define SPI1_BASE  (APB2PERIPH_BASE + 0x3000)

//------------------------------------------------------------------------------

#ifdef __ASSEMBLER__

#define SPI_CTLR1   0
#define SPI_CTLR2   4
#define SPI_STATR   8
#define SPI_DATAR   12
#define SPI_CRCR    16
#define SPI_RCRCR   20
#define SPI_TCRCR   24
#define SPI_HSCR    36

#else

//------------------------------------------------------------------------------

typedef struct {
  __IO uint16_t CTLR1;      /* SPI Control Register 1          */
       uint16_t RESERVED0;
  __IO uint16_t CTLR2;      /* SPI Control Register 1          */
       uint16_t RESERVED1;
  __IO uint16_t STATR;      /* SPI Status Register             */
       uint16_t RESERVED2;
  __IO uint16_t DATAR;      /* SPI Data Register               */
       uint16_t RESERVED3;
  __IO uint16_t CRCR;       /* SPI Polynomial Register         */
       uint16_t RESERVED4;
  __IO uint16_t RCRCR;      /* SPI Receive CRC Register        */
       uint16_t RESERVED5;
  __IO uint16_t TCRCR;      /* SPI Transmit CRC Register       */
       uint16_t RESERVED6;
       uint32_t RESERVED7;
       uint32_t RESERVED8;
  __IO uint16_t HSCR;       /* SPI High-speed control register */
       uint16_t RESERVED9;
} spi_t;

#define SPI1  ((spi_t *)SPI1_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------

/*******************  Bit definition for SPI_CTLR1 register  ********************/
#define SPI_CPHA 0x0001 /* Clock Phase */
#define SPI_CPOL 0x0002 /* Clock Polarity */
#define SPI_MSTR 0x0004 /* Master Selection */

/* Baud Rate Control */
#define SPI_BR        0x0038 /* BR[5:3] bits */
#define SPI_BR_DIV2   0x0000
#define SPI_BR_DIV4   0x0008
#define SPI_BR_DIV8   0x0010
#define SPI_BR_DIV16  0x0018
#define SPI_BR_DIV32  0x0020
#define SPI_BR_DIV64  0x0028
#define SPI_BR_DIV128 0x0030
#define SPI_BR_DIV256 0x0038

#define SPI_SPE      0x0040 /* SPI Enable */
#define SPI_LSBFIRST 0x0080
#define SPI_SSI      0x0100 /* Internal slave select */
#define SPI_SSM      0x0200 /* Software slave management */
#define SPI_DFF      0x0800 /* Data Frame Format */
#define SPI_CRCNEXT  0x1000 /* Transmit CRC next */
#define SPI_CRCEN    0x2000 /* Hardware CRC calculation enable */

/* data direction */
#define SPI_FULLDUPLEX 0x0000  /* MOSI and MISO */
#define SPI_2LINES_RX  0x0400  /* MOSI off */
#define SPI_1LINE_RX   0x8000  /* MISO input */
#define SPI_1LINE_TX   0xC000  /* MISO output */

/*******************  Bit definition for SPI_CTLR2 register  ********************/
#define SPI_RXDMAEN 0x0001 /* Rx Buffer DMA Enable */
#define SPI_TXDMAEN 0x0002 /* Tx Buffer DMA Enable */
#define SPI_SSOE    0x0004 /* SS Output Enable */
#define SPI_ERRIE   0x0020 /* Error Interrupt Enable */
#define SPI_RXNEIE  0x0040 /* RX buffer Not Empty Interrupt Enable */
#define SPI_TXEIE   0x0080 /* Tx buffer Empty Interrupt Enable */

/********************  Bit definition for SPI_STATR register  ********************/
#define SPI_RXNE   0x0001 /* Receive buffer Not Empty */
#define SPI_TXE    0x0002 /* Transmit buffer Empty */
#define SPI_CHSIDE 0x0004 /* Channel side */
#define SPI_UDR    0x0008 /* Underrun flag */
#define SPI_CRCERR 0x0010 /* CRC Error flag */
#define SPI_MODF   0x0020 /* Mode fault */
#define SPI_OVR    0x0040 /* Overrun flag */
#define SPI_BSY    0x0080 /* Busy flag */

/********************  Bit definition for SPI_DATAR register  ********************/
#define SPI_DR 0xFFFF /* Data Register */

/*******************  Bit definition for SPI_CRCR register  ******************/
#define SPI_CRCPOLY 0xFFFF /* CRC polynomial register */

/******************  Bit definition for SPI_RCRCR register  ******************/
#define SPI_RXCRC 0xFFFF /* Rx CRC Register */

/******************  Bit definition for SPI_TCRCR register  ******************/
#define SPI_TXCRC 0xFFFF /* Tx CRC Register */

/******************  Bit definition for SPI_HSCR register  ******************/
#define SPI_HSRXEN 0x0001

//------------------------------------------------------------------------------

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * gadefox, 2026
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
