#pragma once

#include <stdint.h>

#include "wch/hw/base.h"
#include "wch/hw/def.h"

/******************************************************************************/
/*                             System Ticks                                   */
/******************************************************************************/

#define STK_BASE  (CORE_PERIPH_BASE + 0xF000)

//------------------------------------------------------------------------------

#ifdef __ASSEMBLER__

#define STK_CTLR   0
#define STK_SR     4
#define STK_CNTL   8
#define STK_CMPLR  16

#else

//------------------------------------------------------------------------------

/* memory mapped structure for SYSTICK */
typedef struct {
  __IO uint32_t CTLR;       /* System Count Control Register          */
  __IO uint32_t SR;         /* System Count Status Register           */
  __IO uint32_t CNTL;       /* System Counter Register                */
       uint32_t RESERVED;
  __IO uint32_t CMPLR;      /* System Count Comparison Value Register */
} stk_t;

#define STK  ((stk_t *)STK_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------

/*******************  Bit definition for STK_CTLR register  *******************/
#define STK_CTLR_STE    ((uint32_t)0x00000001) /* System counter enable */
#define STK_CTLR_STIE   ((uint32_t)0x00000002) /* Counter interrupt enable */
#define STK_CTLR_STCLK  ((uint32_t)0x00000004) /* Counter clock source (1=HCLK, 0=HCLK/8) */
#define STK_CTLR_STRE   ((uint32_t)0x00000008) /* Auto-reload enable */
#define STK_CTLR_SWIER  ((uint32_t)0x80000000) /* Software interrupt trigger enable */

/*******************  Bit definition for STK_SR register  *******************/
#define STK_SR_CNTIF  ((uint32_t)0x00000001) /* Counting value comparison flag (write 0 to clear) */

//------------------------------------------------------------------------------

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * It was significantly reworked into several files cnlohr, 2025-01-29
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
