#pragma once

#include "wch/hw/def.h"

/******************************************************************************/
/*                            Vendor Registers                                */
/******************************************************************************/

#ifdef __ASSEMBLER__

#define CHIPID_BASE  0x1FFFF704
#define CFG0_BASE    0x1FFFF7D4
#define ESIG_BASE    0x1FFFF7E0

//------------------------------------------------------------------------------

#define CHIPID_REVID  0
#define CHIPID_DEVID  2

//------------------------------------------------------------------------------

#define ESIG_FLACAP  0
#define ESIG_UNIID1  8
#define ESIG_UNIID2  12
#define ESIG_UNIID3  16

#else

//------------------------------------------------------------------------------

typedef struct {
  __I uint16_t REVID;  /* Lower 16 bits of CHIPID */
  __I uint16_t DEVID;  /* Upper 16 bits of CHIPID */
} chipid_t;

#define CHIPID  ((chipid_t *)CHIPID_BASE)

//------------------------------------------------------------------------------

typedef struct {
  __I uint16_t FLACAP;      /* Flash capacity register */
      uint16_t RESERVED0;
      uint32_t RESERVED1;
  __I uint32_t UNIID1;      /* UID register 1 */
  __I uint32_t UNIID2;      /* UID register 2 */
  __I uint32_t UNIID3;      /* UID register 3 */
} esig_t;

#define ESIG  ((esig_t *)ESIG_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * It was significantly reworked into several files cnlohr, 2025-01-29
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
