#pragma once

#include "wch/hw/def.h"

/******************************************************************************/
/*                            Vendor Registers                                */
/******************************************************************************/

#define VNDR_BASE  0x1FFFF7C0
#define VNDR_SIZE  64

//------------------------------------------------------------------------------


#ifdef __ASSEMBLER__

#define VNDR_CHIPID   0x04
#define VNDR_PLLTRIM  0x14
#define VNDR_FLACAP   0x20
#define VNDR_UNIID1   0x28
#define VNDR_UNIID2   0x2C
#define VNDR_UNIID3   0x30

#else

//------------------------------------------------------------------------------

typedef enum {
  DEV_TSSOP20,  // 0
  DEV_QFN20,    // 1
  DEV_SOP16,    // 2
  DEV_SOP8,     // 3
} chip_package_t;

typedef struct {
      uint32_t RESERVED0;
  __I uint32_t CHIPID;
      uint32_t RESERVED1[3];
  __I uint32_t PLLTRIM;
      uint32_t RESERVED2[2];
  __I uint16_t FLACAP;      /* Flash capacity register */
      uint16_t RESERVED3;
      uint32_t RESERVED4;
  __I uint32_t UNIID1;      /* UID register 1 */
  __I uint32_t UNIID2;      /* UID register 2 */
  __I uint32_t UNIID3;      /* UID register 3 */
      uint32_t RESERVED5[3];
} vendor_t;

#define VNDR  ((chipid_t *)VNDR_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------
// NOTE: If REVID's LSB is non-zero, bootloader calls the interrupt controller
// init function (e.g. sets thresholds, clears pending IRQs, enables global
// interrupts).

#define CHIP_REVID    0x0000FFFF        /* 0x0510 */
#define CHIP_PACKAGE  0x000F0000        /* 0x0 */
#define CHIP_DEVID    0xFFF00000        /* 0x003 */

#define CHIP_REVID_POS    0
#define CHIP_PACKAGE_POS  16
#define CHIP_DEVID_POS    20

//------------------------------------------------------------------------------

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * gadefox, 2026
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
