#pragma once

#include "wch/hw/def.h"

/******************************************************************************
 *                             Window WATCHDOG                                *
 ******************************************************************************/

#define WWDG_BASE  (APB1PERIPH_BASE + 0x2C00)

//------------------------------------------------------------------------------

#ifdef __ASSEMBLER__

#define WWDG_CTLR   0
#define WWDG_CFGR   4
#define WWDG_STATR  8

#else

//------------------------------------------------------------------------------

typedef struct {
  __IO uint16_t CTLR;       /* Control Register */
       uint16_t RESERVED0;
  __IO uint16_t CFGR;       /* Configuration Register */
       uint16_t RESERVED1;
  __IO uint16_t STATR;      /* Status Register */
       uint16_t RESERVED2;
} wwdg_t;

#define WWDG  ((wwdg_t *)WWDG_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------

/******************* Bit definition for WWDG_CTLR register ********************/
/* 7-Bit counter (MSB to LSB) */
#define WWDG_TCNT_MSK 0x7F /* T[6:0] bits */

#define WWDG_ACTIVE  0x80 /* Activation bit */

/******************* Bit definition for WWDG_CFGR register *******************/
/* 7-bit window value */
#define WWDG_WIN_MSK 0x007F  /* W[6:0] bits */

/* Timer Base */
#define WWDG_TIM_MSK  0x0180  /* WDGTB[8:7] bits */
#define WWDG_TIM_DIV1 0x0000  /* counting time base = HCLK/4096   */
#define WWDG_TIM_DIV2 0x0080  /* counting time base = HCLK/4096/2 */
#define WWDG_TIM_DIV4 0x0100  /* counting time base = HCLK/4096/4 */
#define WWDG_TIM_DIV8 0x0180  /* counting time base = HCLK/4096/8 */

#define WWDG_EWI 0x0200 /* Early Wakeup Interrupt */

/******************* Bit definition for WWDG_STATR register ********************/
#define WWDG_EWIF 0x0001 /* Early Wakeup Interrupt Flag */

//------------------------------------------------------------------------------

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * gadefox, 2026
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
