#pragma once

#include "wch/hw/base.h"
#include "wch/hw/def.h"

/******************************************************************************
 *                             Window WATCHDOG                                *
 ******************************************************************************/

#define WWDG_BASE  (APB1PERIPH_BASE + 0x2C00)

//------------------------------------------------------------------------------

#ifdef __ASSEMBLER__

#define WWDG_CTLR   0
#define WWDG_CFGR   4
#define WWDG_STATR  8

#else

//------------------------------------------------------------------------------

typedef struct {
  __IO uint16_t CTLR;       /* Control Register */
       uint16_t RESERVED1;
  __IO uint16_t CFGR;       /* Configuration Register */
       uint16_t RESERVED2;
  __IO uint16_t STATR;      /* Status Register */
} wwdg_t;

#define WWDG  ((wwdg_t *)WWDG_BASE)

#endif  /* __ASSEMBLER__ */

//------------------------------------------------------------------------------

/* CTLR register bit mask */
#define CTLR_WDGA_SET ((uint32_t)0x00000080)

/* CFGR register bit mask */
#define CFGR_WDGTB_MASK ((uint32_t)0xFFFFFE7F)
#define CFGR_W_MASK     ((uint32_t)0xFFFFFF80)
#define BIT_MASK        ((uint8_t)0x7F)

/******************* Bit definition for WWDG_CTLR register ********************/
#define WWDG_CTLR_T    ((uint8_t)0x7F) /* T[6:0] bits (7-Bit counter (MSB to LSB)) */
#define WWDG_CTLR_T0   ((uint8_t)0x01) /* Bit 0 */
#define WWDG_CTLR_T1   ((uint8_t)0x02) /* Bit 1 */
#define WWDG_CTLR_T2   ((uint8_t)0x04) /* Bit 2 */
#define WWDG_CTLR_T3   ((uint8_t)0x08) /* Bit 3 */
#define WWDG_CTLR_T4   ((uint8_t)0x10) /* Bit 4 */
#define WWDG_CTLR_T5   ((uint8_t)0x20) /* Bit 5 */
#define WWDG_CTLR_T6   ((uint8_t)0x40) /* Bit 6 */
#define WWDG_CTLR_WDGA ((uint8_t)0x80) /* Activation bit */

/******************* Bit definition for WWDG_CFGR register *******************/
#define WWDG_CFGR_W      ((uint16_t)0x007F) /* W[6:0] bits (7-bit window value) */
#define WWDG_CFGR_W0     ((uint16_t)0x0001) /* Bit 0 */
#define WWDG_CFGR_W1     ((uint16_t)0x0002) /* Bit 1 */
#define WWDG_CFGR_W2     ((uint16_t)0x0004) /* Bit 2 */
#define WWDG_CFGR_W3     ((uint16_t)0x0008) /* Bit 3 */
#define WWDG_CFGR_W4     ((uint16_t)0x0010) /* Bit 4 */
#define WWDG_CFGR_W5     ((uint16_t)0x0020) /* Bit 5 */
#define WWDG_CFGR_W6     ((uint16_t)0x0040) /* Bit 6 */
#define WWDG_CFGR_WDGTB  ((uint16_t)0x0180) /* WDGTB[1:0] bits (Timer Base) */
#define WWDG_CFGR_WDGTB0 ((uint16_t)0x0080) /* Bit 0 */
#define WWDG_CFGR_WDGTB1 ((uint16_t)0x0100) /* Bit 1 */
#define WWDG_CFGR_EWI    ((uint16_t)0x0200) /* Early Wakeup Interrupt */

/******************* Bit definition for WWDG_STATR register ********************/
#define WWDG_STATR_EWIF ((uint8_t)0x01) /* Early Wakeup Interrupt Flag */

/* WWDG_Prescaler */
#define WWDG_PRESCALER_1 ((uint32_t)0x00000000)
#define WWDG_PRESCALER_2 ((uint32_t)0x00000080)
#define WWDG_PRESCALER_4 ((uint32_t)0x00000100)
#define WWDG_PRESCALER_8 ((uint32_t)0x00000180)

//------------------------------------------------------------------------------

/*
 * This file contains various parts of the official WCH EVT Headers which
 * were originally under a restrictive license.
 *
 * The collection of this file was generated by
 * cnlohr, 2023-02-18 and
 * AlexanderMandera, 2023-06-23
 * It was significantly reworked into several files cnlohr, 2025-01-29
 *
 * While originally under a restrictive copyright, WCH has approved use
 * under MIT-licensed use, because of inclusion in Zephyr, as well as other
 * open-source licensed projects.
 *
 * These copies of the headers from WCH are available now under:
 *
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
